services:
  brasa-db-migration:
    container_name: brasa-db-migration
    build:
      context: .
      dockerfile: scraper.Dockerfile
    volumes:
      - .:/project
    command: [ "python3", "brasa/utils/register_bots.py" ]

  brasa-backend:
    container_name: brasa-backend
    depends_on:
      - brasa-db-migration
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - .:/project
      - logs-volume:/var/log
    ports:
      - 8000:8000
    command: [ "gunicorn", "-c", "gunicorn_config.py", "app:app" ]

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - logs-volume:/var/log

volumes:
    logs-volume: 
