server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://loki.regios.com.br/loki/api/v1/push

scrape_configs:
  - job_name: brasa-backend-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: brasa-backend
          __path__: /var/log/brasa.log
